@local=http://localhost:8000

GET {{local}}/posts/




####

POST {{local}}/login/
Content-Type: application/json

{
    "username": "daniel", 
    "password": "Aa123456"
}


####
GET {{local}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5OTgxMTA5LCJpYXQiOjE3Nzk5ODA4MDksImp0aSI6IjdjYWNiM2Q1OTdmNTRjMGRhNDFhY2EwYjgzM2YwYmQwIiwidXNlcl9pZCI6IjEifQ.88QYKroNmlG2-HRZVteHPZ1FLnllnQSW2upwm_IZeYE

###
GET {{local}}/users
Authorization: basic ZGFuaWVsOkFhMTIzNDU2Cg==
