# Generated by Django 6.0.4 on 2026-04-30 17:25

from django.db import migrations
from django.core.management import call_command

from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def load_fixtures(apps: Apps, schema_editor: BaseDatabaseSchemaEditor): 
    call_command('loaddata', 'initial_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures)
    ]
